### ISSUE TITLE
【bug】Mac 端无法退出应用

### ISSUE THREAD

**Issue by Ovilia** [oncework/kuaixieya#6]
感谢作者做了这个很实用的工具，还没开始用，发现一个小问题。

<kbd>CMD</kbd> + <kbd>Q</kbd> 或菜单栏或状态栏点击“退出”都无效，无法退出应用。

**Comment by xudaolong** [comment]
@Ovilia 先进程结束一下，可能有些窗口没处理好。

**Comment by xudaolong** [comment]
@Ovilia v1.2.1 版本修复。
